blueprint:
  name: Bathroom Lights and Fan Control
  description: Manage lights and exhaust fan for a bathroom. This is based on occupancy and humidity.
  domain: automation
  source_url: https://github.com/kenyonj/ha-blueprints/blob/main/bathroom_lights_and_fan_control.yaml
  author: kenyonj
  input:
    enable_humidity_control:
      name: Enable Humidity Control
      description: Enable/Disable humidity-based fan operation.
      default: true
      selector:
        boolean:
    enable_lights_control:
      name: Enable Lights Control
      description: Enable/Disable light control based on occupancy.
      default: true
      selector:
        boolean:
    enable_exhaust_for_toilet:
      name: Enable Toilet Exhaust Fan
      description: Enable/Disable exhaust fan activation for toilet usage.
      default: false
      selector:
        boolean:
    occupancy_sensor:
      name: Occupancy Sensor
      default: ""
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    humidity_sensor:
      name: Humidity Sensor
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity
    lights_to_turn_on:
      name: Lights to turn on
      default: ""
      selector:
        entity:
          domain: light
          multiple: true
    lights_to_turn_off:
      name: Lights to turn off
      default: ""
      selector:
        entity:
          domain: light
          multiple: true
    exhaust_fan_switch:
      name: Exhaust Fan Switch
      default: ""
      selector:
        entity:
          domain: switch
    helper_high_humidity_number:
      name: (Required) Helper - High Humidity Number
      description: Input number for the humidity number that will trigger this automation. You will need to manually create a number input entity for this, please read the blueprint Additional Notes for more info.
      default: 60
      selector:
        number:
          min: 30
          max: 80
          step: 1
          unit_of_measurement: percent
    time_for_fan_to_run_after_unoccupied:
      name: (Required) Helper - Time for fan to run after unoccupied
      description: Input number for the amount of time the exhaust fan should run after the bathroom becomes unoccupied (in seconds).
      default: 600
      selector:
        number:
          min: 60
          max: 3600
          step: 60
          unit_of_measurement: seconds
    time_before_exhaust_fan_turns_on_after_occupied:
      name: (Required) Helper - Time before exhaust fan turns on after occupied
      description: Input number for the amount of time after the bathroom is occupied to wait until turning on the exhaust fan (in seconds).
      default: 120
      selector:
        number:
          min: 60
          max: 3600
          step: 60
          unit_of_measurement: seconds
    time_for_light_to_stay_on_after_unoccupied:
      name: (Required) Helper - Time for light to stay on after unoccupied
      description: Input number for the amount of time the light should stay on after the bathroom becomes unoccupied (in seconds).
      default: 15
      selector:
        number:
          min: 5
          max: 300
          step: 5
          unit_of_measurement: seconds
    helper_humidity_control_is_active:
      name: (Required) Helper - Humidity Control Is Active
      description: Input boolean for whether or not this exhaust fan has been turned on via humidity control automations.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input helper_high_humidity_number
    id: humid
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: !input helper_high_humidity_number
    id: arid
    for:
      minutes: 5
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: occupied
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    id: unoccupied
  # The following two triggers use templates for the 'for:' field to leverage input_number entities
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: occupied_fan
    for:
      seconds: !input time_before_exhaust_fan_turns_on_after_occupied
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    id: unoccupied_fan
    for:
      seconds: !input time_for_fan_to_run_after_unoccupied

variables:
  enable_lights_control: !input enable_lights_control
  enable_humidity_control: !input enable_humidity_control
  enable_exhaust_for_toilet: !input enable_exhaust_for_toilet
  humidity_sensor: !input humidity_sensor
  occupancy_sensor: !input occupancy_sensor
  lights_to_turn_on: !input lights_to_turn_on
  lights_to_turn_off: !input lights_to_turn_off
  exhaust_fan_switch: !input exhaust_fan_switch
  helper_humidity_control_is_active: !input helper_humidity_control_is_active
  time_for_fan_to_run_after_unoccupied: !input time_for_fan_to_run_after_unoccupied
  time_for_light_to_stay_on_after_unoccupied: !input time_for_light_to_stay_on_after_unoccupied
  time_before_exhaust_fan_turns_on_after_occupied: !input time_before_exhaust_fan_turns_on_after_occupied

action:
  - choose:
      # Light Control
      - conditions:
          - condition: trigger
            id: occupied
          - condition: template
            value_template: "{{ enable_lights_control }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input lights_to_turn_on
      - conditions:
          - condition: trigger
            id: unoccupied
          - condition: template
            value_template: "{{ enable_lights_control }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input lights_to_turn_off

      # Exhaust For Toilet
      - conditions:
          - condition: trigger
            id: occupied_fan
          - condition: template
            value_template: "{{ enable_exhaust_for_toilet }}"
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: !input exhaust_fan_switch
      - conditions:
          - condition: trigger
            id: unoccupied_fan
          - condition: template
            value_template: "{{ enable_exhaust_for_toilet }}"
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "on"
          - service: switch.turn_off
            target:
              entity_id: !input exhaust_fan_switch

      # Humidity Control
      - conditions:
          - condition: trigger
            id: humid
          - condition: template
            value_template: "{{ enable_humidity_control }}"
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: !input exhaust_fan_switch
          - service: input_boolean.turn_on
            target:
              entity_id: !input helper_humidity_control_is_active
      - conditions:
          - condition: trigger
            id: arid
          - condition: template
            value_template: "{{ enable_humidity_control }}"
          - condition: state
            entity_id: !input helper_humidity_control_is_active
            state: "on"
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "on"
          - service: switch.turn_off
            target:
              entity_id: !input exhaust_fan_switch
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_humidity_control_is_active
