blueprint:
  name: Bathroom Lights and Fan Control
  description: Manage lights and exhaust fan for a bathroom. This is based on occupancy and humidity.
  domain: automation
  source_url: https://github.com/kenyonj/ha-blueprints/blob/main/bathroom_lights_and_fan_control.yaml
  author: kenyonj
  input:
    occupancy_sensor:
      name: Occupancy Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy
    humidity_sensor:
      name: Humidity Sensor
      selector:
        entity:
          domain: sensor
          device_class: humidity
    light_switch:
      name: Light Switch
      selector:
        entity:
          domain: light
    exhaust_fan_switch:
      name: Exhaust Fan Switch
      selector:
        entity:
          domain: switch
    helper_high_humidity_number:
      name: (Required) Helper - High Humidity Number
      description: Input number for the humidity number that will trigger this automation. You will need to manually create a number input entity for this, please read the blueprint Additional Notes for more info.
      selector:
        entity:
          domain: input_number
    helper_time_for_fan_to_run_after_unoccupied:
      name: (Required) Helper - Time for fan to run after unoccupied
      description: Input number for the amount of time the exhaust fan should run after the bathroom becomes unoccupied (in seconds).
      selector:
        entity:
          domain: input_number
    helper_time_before_exhaust_fan_turns_on_after_occupied:
      name: (Required) Helper - Time before exhaust fan turns on after occupied
      description: Input number for the amount of time after the bathroom is occupied to wait until turning on the exhaust fan (in seconds).
      selector:
        entity:
          domain: input_number
    helper_time_for_light_to_stay_on_after_unoccupied:
      name: (Required) Helper - Time for light to stay on after unoccupied
      description: Input number for the amount of time the light should stay on after the bathroom becomes unoccupied (in seconds).
      selector:
        entity:
          domain: input_number
    helper_humidity_control_is_active:
      name: (Required) Helper - Humidity Control Is Active
      description: Input boolean for whether or not this exhaust fan has been turned on via humidity control automations.
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: numeric_state
    entity_id: !input humidity_sensor
    above: !input helper_high_humidity_number
    id: humid
  - platform: numeric_state
    entity_id: !input humidity_sensor
    below: !input helper_high_humidity_number
    id: arid
    for:
      minutes: 5
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: occupied
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    id: unoccupied
  # The following two triggers use templates for the 'for:' field to leverage input_number entities
  - platform: state
    entity_id: !input occupancy_sensor
    from: "off"
    to: "on"
    id: occupied_fan
    for:
      seconds: "{{ states(!input helper_time_before_exhaust_fan_turns_on_after_occupied) | int }}"
  - platform: state
    entity_id: !input occupancy_sensor
    from: "on"
    to: "off"
    id: unoccupied_fan
    for:
      seconds: "{{ states(!input helper_time_for_fan_to_run_after_unoccupied) | int }}"

variables:
  humidity_sensor: !input humidity_sensor
  occupancy_sensor: !input occupancy_sensor
  light_switch: !input light_switch
  exhaust_fan_switch: !input exhaust_fan_switch
  helper_humidity_control_is_active: !input helper_humidity_control_is_active
  helper_time_for_fan_to_run_after_unoccupied: !input helper_time_for_fan_to_run_after_unoccupied
  helper_time_for_light_to_stay_on_after_unoccupied: !input helper_time_for_light_to_stay_on_after_unoccupied
  helper_time_before_exhaust_fan_turns_on_after_occupied: !input helper_time_before_exhaust_fan_turns_on_after_occupied

action:
  - choose:
      - conditions:
          - condition: trigger
            id: occupied
          - condition: state
            entity_id: !input light_switch
            state: "off"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_switch
      - conditions:
          - condition: trigger
            id: unoccupied
          - condition: state
            entity_id: !input light_switch
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_switch
      - conditions:
          - condition: trigger
            id: occupied_fan
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: !input exhaust_fan_switch
      - conditions:
          - condition: trigger
            id: unoccupied_fan
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "on"
          - service: switch.turn_off
            target:
              entity_id: !input exhaust_fan_switch
      - conditions:
          - condition: trigger
            id: humid
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "off"
          - service: switch.turn_on
            target:
              entity_id: !input exhaust_fan_switch
          - service: input_boolean.turn_on
            target:
              entity_id: !input helper_humidity_control_is_active
      - conditions:
          - condition: trigger
            id: arid
          - condition: state
            entity_id: !input helper_humidity_control_is_active
            state: "on"
        sequence:
          - condition: state
            entity_id: !input exhaust_fan_switch
            state: "on"
          - service: switch.turn_off
            target:
              entity_id: !input exhaust_fan_switch
          - service: input_boolean.turn_off
            target:
              entity_id: !input helper_humidity_control_is_active
